version: '3.4'
services:
  silajs:
    build:
      context: .
      dockerfile: ../Dockerfile
    container_name: silajs
    volumes:
      - ./datadir:/datadir
    command: >
      --dataDir=/datadir
    network_mode: host
